const TEST = 'TEST';
const SET_REF = 'SET_REF';
const SET_TOOL = 'SET_TOOL';
const SET_FILL_COLOR = 'SET_FILL_COLOR';
const SET_STROKE_COLOR = 'SET_STROKE_COLOR';
const SET_LINE_WIDTH = 'SET_LINE_WIDTH';
const PUSH_TO_UNDO = 'PUSH_TO_UNDO';
const PUSH_TO_REDO = 'PUSH_TO_REDO';
const UNDO = 'UNDO';
const REDO = 'REDO';
const DELETE_STATE = 'DELETE_STATE';
const DRAW = 'DRAW';
const ADD_PAINT = 'ADD_PAINT';
const SET_PAINT = 'SET_PAINT';
const SAVE_PAINT = 'SAVE_PAINT';
const CLEAR_UNDO_REDO = 'CLEAR_UNDO_REDO';
const GET_DOCUMENT_DATA_BY_UID = 'GET_DOCUMENT_DATA_BY_UID';

export {
  TEST,
  SET_REF,
  SET_TOOL,
  SET_FILL_COLOR,
  SET_STROKE_COLOR,
  SET_LINE_WIDTH,
  PUSH_TO_UNDO,
  PUSH_TO_REDO,
  UNDO,
  REDO,
  DELETE_STATE,
  DRAW,
  ADD_PAINT,
  SET_PAINT,
  SAVE_PAINT,
  CLEAR_UNDO_REDO,
  GET_DOCUMENT_DATA_BY_UID,
};
